import { readdirSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Parse the first YAML-ish frontmatter block; returns name + description only. */
function parseSkillFrontmatter(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return { name: "", description: "" };
  const block = m[1];
  const name = (block.match(/^name:\s*(.+)$/m)?.[1] ?? "").trim().replace(/^["']|["']$/g, "");
  const descQuoted = block.match(/^description:\s*"((?:[^"\\]|\\.)+)"$/m);
  const descPlain = block.match(/^description:\s*(?!>|\|)(.+)$/m);
  let description = (descQuoted?.[1] ?? descPlain?.[1] ?? "").trim();
  if (descQuoted) description = description.replace(/\\(.)/g, "$1");
  return { name, description };
}

/** Build the skills index. `skillsRelDir` is relative to this file's dir. */
export function buildIndex(skillsRelDir) {
  const root = join(__dirname, skillsRelDir);
  const pkg = JSON.parse(readFileSync(join(__dirname, "package.json"), "utf8"));
  const skills = [];
  for (const slug of readdirSync(root).sort()) {
    const dir = join(root, slug);
    if (!statSync(dir).isDirectory()) continue;
    let skillMd = "";
    try { skillMd = readFileSync(join(dir, "SKILL.md"), "utf8"); } catch { continue; }
    const fm = parseSkillFrontmatter(skillMd);

    let meta = null;
    try { meta = JSON.parse(readFileSync(join(dir, "_meta.json"), "utf8")); } catch { /* example skill */ }

    const entry = {
      slug,
      path: `skills/${slug}`,
      label: meta?.managed?.label ?? fm.name ?? slug,
      description: meta?.managed?.description ?? fm.description ?? "",
      version: meta?.version ?? "1.0.0",
      origin: meta?.managed ? "opcify" : "example",
    };
    if (meta?.managed) {
      entry.emoji = meta.managed.emoji;
      entry.managed = {
        tier: meta.managed.tier === "template-scoped" ? "template-scoped" : "general",
        templateScopes: Array.isArray(meta.managed.templateScopes) ? meta.managed.templateScopes : [],
        alwaysOn: meta.managed.alwaysOn === true,
      };
    }
    skills.push(entry);
  }
  return { version: pkg.version, repo: "opcify/skills", skills };
}

function emit(idx) {
  const js = `// AUTO-GENERATED by index/build.mjs — do not edit.\nexport default ${JSON.stringify(idx, null, 2)};\n`;
  writeFileSync(join(__dirname, "index.js"), js);
  const dts = `export interface ManagedBlock {\n  tier: "general" | "template-scoped";\n  templateScopes: string[];\n  alwaysOn: boolean;\n}\nexport interface SkillIndexEntry {\n  slug: string;\n  path: string;\n  label: string;\n  description: string;\n  version: string;\n  origin: "opcify" | "example";\n  emoji?: string;\n  managed?: ManagedBlock;\n}\nexport interface SkillsIndex {\n  version: string;\n  repo: string;\n  skills: SkillIndexEntry[];\n}\ndeclare const index: SkillsIndex;\nexport default index;\n`;
  writeFileSync(join(__dirname, "index.d.ts"), dts);
}

// Run as a script (not when imported by the test).
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  emit(buildIndex("../skills"));
  console.log("Wrote index/index.js + index/index.d.ts");
}
