// AUTO-GENERATED by index/build.mjs — do not edit.
export default {
  "version": "1.0.0",
  "repo": "opcify/skills",
  "skills": [
    {
      "slug": "algorithmic-art",
      "path": "skills/algorithmic-art",
      "label": "algorithmic-art",
      "description": "Creating algorithmic art using p5.js with seeded randomness and interactive parameter exploration. Use this when users request creating art using code, generative art, algorithmic art, flow fields, or particle systems. Create original algorithmic art rather than copying existing artists' work to avoid copyright violations.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "alpha-vantage-findata",
      "path": "skills/alpha-vantage-findata",
      "label": "Alpha Vantage",
      "description": "Global stock quotes, OHLCV history, fundamentals, technical indicators, news + sentiment, FX, crypto, and macro data via Alpha Vantage's official REST API",
      "version": "0.1.0",
      "origin": "opcify",
      "emoji": "🌐",
      "managed": {
        "tier": "template-scoped",
        "templateScopes": [
          "investing_trading_firm"
        ],
        "alwaysOn": false
      }
    },
    {
      "slug": "amazon-s3-storage",
      "path": "skills/amazon-s3-storage",
      "label": "Amazon S3",
      "description": "Upload, download, list, and manage files in Amazon S3 buckets",
      "version": "0.1.0",
      "origin": "opcify",
      "emoji": "📦",
      "managed": {
        "tier": "general",
        "templateScopes": [],
        "alwaysOn": false
      }
    },
    {
      "slug": "brand-guidelines",
      "path": "skills/brand-guidelines",
      "label": "brand-guidelines",
      "description": "Applies Anthropic's official brand colors and typography to any sort of artifact that may benefit from having Anthropic's look-and-feel. Use it when brand colors or style guidelines, visual formatting, or company design standards apply.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "browser-use",
      "path": "skills/browser-use",
      "label": "Browser Automation",
      "description": "Web browsing, form filling, screenshots, and data extraction",
      "version": "2.0.0",
      "origin": "opcify",
      "emoji": "🌐",
      "managed": {
        "tier": "general",
        "templateScopes": [],
        "alwaysOn": true
      }
    },
    {
      "slug": "canvas-design",
      "path": "skills/canvas-design",
      "label": "canvas-design",
      "description": "Create beautiful visual art in .png and .pdf documents using design philosophy. You should use this skill when the user asks to create a poster, piece of art, design, or other static piece. Create original visual designs, never copying existing artists' work to avoid copyright violations.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "claude-api",
      "path": "skills/claude-api",
      "label": "claude-api",
      "description": "Build, debug, and optimize Claude API / Anthropic SDK apps. Apps built with this skill should include prompt caching. Also handles migrating existing Claude API code between Claude model versions (4.5 → 4.6, 4.6 → 4.7, retired-model replacements). TRIGGER when: code imports `anthropic`/`@anthropic-ai/sdk`; user asks for the Claude API, Anthropic SDK, or Managed Agents; user adds/modifies/tunes a Claude feature (caching, thinking, compaction, tool use, batch, files, citations, memory) or model (Opus/Sonnet/Haiku) in a file; questions about prompt caching / cache hit rate in an Anthropic SDK project. SKIP: file imports `openai`/other-provider SDK, filename like `*-openai.py`/`*-generic.py`, provider-neutral code, general programming/ML.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "cloudflare-r2-storage",
      "path": "skills/cloudflare-r2-storage",
      "label": "Cloudflare R2",
      "description": "Upload, download, list, and manage files in Cloudflare R2 buckets (S3-compatible, zero egress fees)",
      "version": "0.1.0",
      "origin": "opcify",
      "emoji": "🔶",
      "managed": {
        "tier": "general",
        "templateScopes": [],
        "alwaysOn": false
      }
    },
    {
      "slug": "doc-coauthoring",
      "path": "skills/doc-coauthoring",
      "label": "doc-coauthoring",
      "description": "Guide users through a structured workflow for co-authoring documentation. Use when user wants to write documentation, proposals, technical specs, decision docs, or similar structured content. This workflow helps users efficiently transfer context, refine content through iteration, and verify the doc works for readers. Trigger when user mentions writing docs, creating proposals, drafting specs, or similar documentation tasks.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "docx",
      "path": "skills/docx",
      "label": "docx",
      "description": "Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files). Triggers include: any mention of 'Word doc', 'word document', '.docx', or requests to produce professional documents with formatting like tables of contents, headings, page numbers, or letterheads. Also use when extracting or reorganizing content from .docx files, inserting or replacing images in documents, performing find-and-replace in Word files, working with tracked changes or comments, or converting content into a polished Word document. If the user asks for a 'report', 'memo', 'letter', 'template', or similar deliverable as a Word or .docx file, use this skill. Do NOT use for PDFs, spreadsheets, Google Docs, or general coding tasks unrelated to document generation.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "frontend-design",
      "path": "skills/frontend-design",
      "label": "frontend-design",
      "description": "Create distinctive, production-grade frontend interfaces with high design quality. Use this skill when the user asks to build web components, pages, artifacts, posters, or applications (examples include websites, landing pages, dashboards, React components, HTML/CSS layouts, or when styling/beautifying any web UI). Generates creative, polished code and UI design that avoids generic AI aesthetics.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "google-cloud-storage",
      "path": "skills/google-cloud-storage",
      "label": "Google Cloud Storage",
      "description": "Upload, download, list, and manage files in Google Cloud Storage buckets",
      "version": "0.1.0",
      "origin": "opcify",
      "emoji": "☁️",
      "managed": {
        "tier": "general",
        "templateScopes": [],
        "alwaysOn": false
      }
    },
    {
      "slug": "internal-comms",
      "path": "skills/internal-comms",
      "label": "internal-comms",
      "description": "A set of resources to help me write all kinds of internal communications, using the formats that my company likes to use. Claude should use this skill whenever asked to write some sort of internal communications (status reports, leadership updates, 3P updates, company newsletters, FAQs, incident reports, project updates, etc.).",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "mcp-builder",
      "path": "skills/mcp-builder",
      "label": "mcp-builder",
      "description": "Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. Use when building MCP servers to integrate external APIs or services, whether in Python (FastMCP) or Node/TypeScript (MCP SDK).",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "opcify",
      "path": "skills/opcify",
      "label": "Opcify",
      "description": "Task management & API callbacks. Reports status and results back to Opcify.",
      "version": "1.0.0",
      "origin": "opcify",
      "emoji": "⚙️",
      "managed": {
        "tier": "general",
        "templateScopes": [],
        "alwaysOn": true
      }
    },
    {
      "slug": "opcify-docx",
      "path": "skills/opcify-docx",
      "label": "DOCX Documents",
      "description": "Word document creation, editing, and formatting",
      "version": "1.0.0",
      "origin": "opcify",
      "emoji": "📝",
      "managed": {
        "tier": "general",
        "templateScopes": [],
        "alwaysOn": false
      }
    },
    {
      "slug": "opcify-pdf",
      "path": "skills/opcify-pdf",
      "label": "PDF Documents",
      "description": "PDF generation, form filling, and reformatting",
      "version": "1.0.0",
      "origin": "opcify",
      "emoji": "📄",
      "managed": {
        "tier": "general",
        "templateScopes": [],
        "alwaysOn": false
      }
    },
    {
      "slug": "opcify-pptx",
      "path": "skills/opcify-pptx",
      "label": "PowerPoint",
      "description": "Presentation generation, editing, and reading",
      "version": "1.0.0",
      "origin": "opcify",
      "emoji": "📽️",
      "managed": {
        "tier": "general",
        "templateScopes": [],
        "alwaysOn": false
      }
    },
    {
      "slug": "opcify-xlsx",
      "path": "skills/opcify-xlsx",
      "label": "Excel Spreadsheets",
      "description": "Excel create, read, analyze, edit, and validate",
      "version": "1.0.0",
      "origin": "opcify",
      "emoji": "📊",
      "managed": {
        "tier": "general",
        "templateScopes": [],
        "alwaysOn": false
      }
    },
    {
      "slug": "pdf",
      "path": "skills/pdf",
      "label": "pdf",
      "description": "Use this skill whenever the user wants to do anything with PDF files. This includes reading or extracting text/tables from PDFs, combining or merging multiple PDFs into one, splitting PDFs apart, rotating pages, adding watermarks, creating new PDFs, filling PDF forms, encrypting/decrypting PDFs, extracting images, and OCR on scanned PDFs to make them searchable. If the user mentions a .pdf file or asks to produce one, use this skill.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "pptx",
      "path": "skills/pptx",
      "label": "pptx",
      "description": "Use this skill any time a .pptx file is involved in any way — as input, output, or both. This includes: creating slide decks, pitch decks, or presentations; reading, parsing, or extracting text from any .pptx file (even if the extracted content will be used elsewhere, like in an email or summary); editing, modifying, or updating existing presentations; combining or splitting slide files; working with templates, layouts, speaker notes, or comments. Trigger whenever the user mentions \"deck,\" \"slides,\" \"presentation,\" or references a .pptx filename, regardless of what they plan to do with the content afterward. If a .pptx file needs to be opened, created, or touched, use this skill.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "project-manager",
      "path": "skills/project-manager",
      "label": "Project Manager",
      "description": "Closed-loop project orchestrator. Plan creation (interactive Q&A or self-evaluating refiner), task dispatch, monitoring with proactive triggers, idea-update plan diffs, paste-in context extraction with prompt-injection isolation, adaptive memory across projects.",
      "version": "1.0.0",
      "origin": "opcify",
      "managed": {
        "tier": "general",
        "templateScopes": [],
        "alwaysOn": true
      }
    },
    {
      "slug": "quotation",
      "path": "skills/quotation",
      "label": "Quotation",
      "description": "Draft, send, and convert quotes. One command end-to-end — client capture, email, shareable link, PDF, and invoice conversion.",
      "version": "1.0.0",
      "origin": "opcify",
      "emoji": "📄",
      "managed": {
        "tier": "general",
        "templateScopes": [],
        "alwaysOn": true
      }
    },
    {
      "slug": "skill-creator",
      "path": "skills/skill-creator",
      "label": "skill-creator",
      "description": "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to create a skill from scratch, edit, or optimize an existing skill, run evals to test a skill, benchmark skill performance with variance analysis, or optimize a skill's description for better triggering accuracy.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "slack-gif-creator",
      "path": "skills/slack-gif-creator",
      "label": "slack-gif-creator",
      "description": "Knowledge and utilities for creating animated GIFs optimized for Slack. Provides constraints, validation tools, and animation concepts. Use when users request animated GIFs for Slack like \"make me a GIF of X doing Y for Slack.\"",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "theme-factory",
      "path": "skills/theme-factory",
      "label": "theme-factory",
      "description": "Toolkit for styling artifacts with a theme. These artifacts can be slides, docs, reportings, HTML landing pages, etc. There are 10 pre-set themes with colors/fonts that you can apply to any artifact that has been creating, or can generate a new theme on-the-fly.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "web-artifacts-builder",
      "path": "skills/web-artifacts-builder",
      "label": "web-artifacts-builder",
      "description": "Suite of tools for creating elaborate, multi-component claude.ai HTML artifacts using modern frontend web technologies (React, Tailwind CSS, shadcn/ui). Use for complex artifacts requiring state management, routing, or shadcn/ui components - not for simple single-file HTML/JSX artifacts.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "web-search",
      "path": "skills/web-search",
      "label": "Web Search",
      "description": "DuckDuckGo-powered web, news, image, and video search with text/markdown/JSON output",
      "version": "1.0.0",
      "origin": "opcify",
      "emoji": "🔎",
      "managed": {
        "tier": "general",
        "templateScopes": [],
        "alwaysOn": false
      }
    },
    {
      "slug": "webapp-testing",
      "path": "skills/webapp-testing",
      "label": "webapp-testing",
      "description": "Toolkit for interacting with and testing local web applications using Playwright. Supports verifying frontend functionality, debugging UI behavior, capturing browser screenshots, and viewing browser logs.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "xlsx",
      "path": "skills/xlsx",
      "label": "xlsx",
      "description": "Use this skill any time a spreadsheet file is the primary input or output. This means any task where the user wants to: open, read, edit, or fix an existing .xlsx, .xlsm, .csv, or .tsv file (e.g., adding columns, computing formulas, formatting, charting, cleaning messy data); create a new spreadsheet from scratch or from other data sources; or convert between tabular file formats. Trigger especially when the user references a spreadsheet file by name or path — even casually (like \"the xlsx in my downloads\") — and wants something done to it or produced from it. Also trigger for cleaning or restructuring messy tabular data files (malformed rows, misplaced headers, junk data) into proper spreadsheets. The deliverable must be a spreadsheet file. Do NOT trigger when the primary deliverable is a Word document, HTML report, standalone Python script, database pipeline, or Google Sheets API integration, even if tabular data is involved.",
      "version": "1.0.0",
      "origin": "example"
    },
    {
      "slug": "yahoo-finance",
      "path": "skills/yahoo-finance",
      "label": "Yahoo Finance",
      "description": "Stock quotes, OHLCV history, technical indicators, financials, options, and analyst data",
      "version": "2.0.0",
      "origin": "opcify",
      "emoji": "📈",
      "managed": {
        "tier": "template-scoped",
        "templateScopes": [
          "investing_trading_firm"
        ],
        "alwaysOn": false
      }
    }
  ]
};
